### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by tbobm** [kitsunde/django-ace-editor#3]
Hi, I'm using Django 2.0.1, and it seems like some feature `django-ace-editor` are now removed.

See the following stacktrace:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/tmp/ace/example/.env/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/tmp/ace/example/.env/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/tmp/ace/example/.env/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/tmp/ace/example/.env/lib/python3.5/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/tmp/ace/example/.env/lib/python3.5/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/tmp/ace/example/.env/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 58, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/tmp/ace/example/.env/lib/python3.5/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/tmp/ace/example/.env/lib/python3.5/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/tmp/ace/example/.env/lib/python3.5/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/tmp/ace/example/.env/lib/python3.5/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/tmp/ace/example/.env/lib/python3.5/site-packages/django/urls/resolvers.py", line 397, in check
    for pattern in self.url_patterns:
  File "/tmp/ace/example/.env/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tmp/ace/example/.env/lib/python3.5/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/tmp/ace/example/.env/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tmp/ace/example/.env/lib/python3.5/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/tmp/ace/example/.env/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/tmp/ace/example/example/urls.py", line 1, in <module>
    from django.conf.urls import patterns, include, url
ImportError: cannot import name 'patterns'
```

I'll try to make a PR if I manage to make it compatible.

**Comment by kitsunde** [comment]
I haven’t maintained this project for many years but there used to be a fork that was maintained so maybe try that.

________________________________

**Comment by tbobm** [comment]
It looks like your version is the last one updated, sadly. I'm going to try to find a working fork, even though I don't think it will be succesful
Thanks for the quick answer

**Comment by kitsunde** [comment]
Not according the fork list. https://github.com/kitsunde/django-ace-editor/network

________________________________

**Comment by tbobm** [comment]
Oh, I don't know why but I mistook your fork for  bradleyayers' one.

Thanks a lot @kitsunde !
